### ISSUE TITLE
Can't install locally because of a syntax error thrown by rollup

### ISSUE THREAD

**Issue by Yoone** [LoicMahieu/react-styled-flexboxgrid#83]
I am trying to install this project locally as I need it as a dependency in my React 16.0.0 project (the current npm version doesn't yet support React 16.0.0, so I'm trying to install it as a git dependency with [`npm-git-install`](https://www.npmjs.com/package/npm-git-install)).

But I am getting an error from rollup when running `npm install` (which runs `rollup -c && cross-env NODE_ENV=production rollup -c`):

```
> rollup -c && cross-env NODE_ENV=production rollup -c

Creating development bundle...

src/index.js → dist/styled-flexboxgrid.js, dist/styled-flexboxgrid.es.js...
[!] (commonjs plugin) SyntaxError: Unexpected token (29:4) in ~/projects/react-styled-flexboxgrid/src/config.js
src/config.js (29:4)
SyntaxError: Unexpected token (29:4) in ~/projects/react-styled-flexboxgrid/src/config.js
    at error (~/projects/react-styled-flexboxgrid/node_modules/rollup/dist/rollup.js:185:14)
    at Promise.resolve.then.catch.err (~/projects/react-styled-flexboxgrid/node_modules/rollup/dist/rollup.js:9448:6)
```

I clearly see that `transform-object-rest-spread` is loaded as a plugin in `.babelrc` and `rollup.config.js` loads it from there, which I checked by printing this line:
`plugins: babelrc.plugins.concat(['external-helpers'])`.

I'm not sure what's going on here, but it looks like maybe the babel spread plugin isn't called during transpiling before rollup bundles it. Has anyone else had that error before? Am I missing a global dependency that's not specified in the `package.json`?

--------

__Edit:__ Alternatively, when is the next release due? Because that would also fix my problem.

**Comment by LoicMahieu** [comment]
I don't know how you get this error. I try to clone this repo + `npm install` and I don't have any problem. Rollup build works well. 
Maybe try to re-install modules, cleanup your npm cache ?

Indeed I forget to publish a new version with the support of React v16.
Done:
+ react-styled-flexboxgrid@2.1.1

**Comment by Yoone** [comment]
Nope, still getting the error. Anyway, the latter worked, thanks!

Your README still says React 0.14 || React 15 though.

**Comment by LoicMahieu** [comment]
Ok the issue happens on travis: https://travis-ci.org/LoicMahieu/react-styled-flexboxgrid/jobs/295239239

I will look at this ASAP

**Comment by Yoone** [comment]
In that case my best guess is that it's either an environment issue or a missing package installed globally (maybe you have rollup installed globally under a more recent version?)

Don't hesitate to send me an email if you'd like me to run other tests. My address can be found on my profile.

**Comment by LoicMahieu** [comment]
Should be fixed now. Reopen if needed
